# _config.yml

title: "Introduction to DevOps"
description: "A course about Introduction to DevOps"
baseurl: "/Introduction-to-DevOps"
url: "https://phuongvo9.github.io"
author:
  name: Phuong Vo
  email: phuongvo9@github.io
github_username: phuongvo9
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - _site
  - README.md
  - .gitignore
  - .DS_Store

collections:
  modules:
    output: true
    permalink: /modules/:name/
  lessons:
    output: true
    permalink: /modules/:module/:name/